FROM ghcr.io/astral-sh/uv:0.12.22@sha256:f513a91fc62fe7c17567eee97230dd198e43edb8a9fbecca843714a4358fe1bc AS uv_source

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.10.3@sha256:dab45abca3ca83695d442018692f4f8a0f41955871c57e6101d7f89a92375caa AS builder

COPY --from=uv_source /uv /uvx /bin/

WORKDIR /build

COPY uv.lock pyproject.toml /build/
COPY ./packages/ /build/packages/

ENV UV_PROJECT_ENVIRONMENT=/venv
ENV UV_PYTHON=/usr/bin/python3
ENV UV_PYTHON_PREFERENCE=only-system

RUN apt-get update \
    && apt-get install --assume-yes --no-install-recommends tini

RUN uv sync --frozen --no-dev --no-editable --package geoprocessor-raster

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.10.3@sha256:dab45abca3ca83695d442018692f4f8a0f41955871c57e6101d7f89a92375caa

ARG GIT_HASH
ENV GIT_HASH=$GIT_HASH
ARG GIT_VERSION
ENV GIT_VERSION=$GIT_VERSION

COPY --from=builder /usr/bin/tini /usr/bin/tini
COPY --from=builder /venv /venv

ENV PATH="/venv/bin:$PATH"
# TODO: Is this still needed?
ENV GTIFF_SRS_SOURCE="EPSG"

WORKDIR /app

ENTRYPOINT ["/usr/bin/tini", "--"]
